version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my_network

  backend:
    build: .
    command: uvicorn backend.api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - my_network

  bot:
    build: .
    command: python bot/bot.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
